# Generated by Django 2.0.2 on 2018-04-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFicha', models.CharField(max_length=20, unique=True)),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
                ('ambiente', models.CharField(max_length=50)),
                ('lider', models.CharField(max_length=100)),
                ('fechaFinEtapaLectiva', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('Enfermedad', 'Enfermedad'), ('Accidente', 'Accidente'), ('Calamidad domestica', 'Calamidad domestica'), ('Otro', 'Otro')], max_length=45)),
                ('solicitoPermisoPor', models.CharField(blank=True, max_length=300, null=True)),
                ('permisoPorHora', models.CharField(blank=True, max_length=45, null=True)),
                ('permisoPorDias', models.CharField(blank=True, max_length=45, null=True)),
                ('horaSalida', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En Espera', 'En Espera'), ('Aprobado', 'Aprobado'), ('Cancelado', 'Cancelado'), ('Rechazado', 'Rechazado'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('vigilante', models.CharField(blank=True, max_length=100, null=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentoIdentidad', models.CharField(max_length=20, unique=True)),
                ('primerNombre', models.CharField(max_length=45)),
                ('segundoNombre', models.CharField(blank=True, max_length=45, null=True)),
                ('primerApellido', models.CharField(max_length=45)),
                ('segundoApellido', models.CharField(blank=True, max_length=45, null=True)),
                ('contacto', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona_ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Ficha')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigoPrograma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='persona_ficha',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Programa'),
        ),
        migrations.AddField(
            model_name='permiso_persona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Persona'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSena.Programa'),
        ),
    ]
